email update confirmation without tests
azine/FOSUserBundle pull request #3
Opened 2017-02-06 10:18 UTC by eugene-o-z

2017-02-06 14:23 UTC, azine commented
looks good. please move the tests as well, where it is possible.

2017-03-06 23:32 UTC, azine requested changes

2017-03-06 23:32 UTC, azine commented on Doctrine/EmailUpdateListener.php
> +    public function __construct(ContainerInterface $container)
Don't inject the container. Inject what you need, but not the whole container.

2017-03-06 23:32 UTC, azine commented on Doctrine/EmailUpdateListener.php
> +            $emailUpdateConfirmation = $this->container->get('azine_platform.emailupdateconfirmation');
I guess this is the wrong reference. There should be no trace of "azine_platform" in the FOSUserBundle.
IMHO a type-hint for $emailUpdateConfirmation would be nice.

2017-03-06 23:32 UTC, azine commented on Doctrine/EmailUpdateListener.php
> +
"cast" the $object here.
```
/** @var UserInterface $user */
$user = $object;
```

and then use $user instead of $object further below.

2017-03-06 23:32 UTC, azine commented on Doctrine/EmailUpdateListener.php
> +                $currentEmail = $args->getEntityChangeSet()['email'][0];
IMHO $currentEmail is a poor choice for the variable name. Does it mean the old or the new one? We're just about to change it... I would use $oldEmail and $newEmail

2017-03-06 23:32 UTC, azine commented on Doctrine/EmailUpdateListener.php
> +                $object->setConfirmationToken(null);
doesn't this need to be flushed to the database?

2017-03-06 23:32 UTC, azine commented on Mailer/TwigSwiftMailer.php
> +     * @param $templateName
this parameter does not exist (anymore?!)

2017-03-06 23:32 UTC, azine commented on Resources/translations/FOSUserBundle.de.yml
> +        info: 'Bitte bestätigen Sie Ihre E-Mail-Adresse'
This is a reminder for myself: update translations

2017-03-06 23:32 UTC, azine commented on Resources/translations/FOSUserBundle.en.yml
> +        info: 'Please confirm your email address'
This is a reminder for myself: update translations

2017-05-13 16:48 UTC, eugene-o-z commented on Doctrine/EmailUpdateListener.php
> +                $object->setConfirmationToken(null);
But this is a preUpdate lifecycle for user object, it will be flushed further.

2017-05-15 08:20 UTC, azine approved these changes

2017-06-13 09:03 UTC, merged